name: ai_imagez
description: "WizardAi"
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter_image_compress: ^2.1.0
  http: ^1.1.2
  image_gallery_saver: ^2.0.3
  share: ^2.0.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  package_info_plus: ^5.0.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  flutter_html: ^3.0.0-beta.2
  image: ^4.1.4
  path: ^1.8.3
  fluttertoast: ^8.0.8
  image_compare_slider: ^2.8.0
  permission_handler: ^11.2.0
  video_player: ^2.8.2
  http_parser: ^4.0.2
  async: ^2.8.2
  chewie: ^1.7.4
  getwidget: ^4.0.0
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.8
  provider: ^6.1.1
  url_launcher: ^6.2.3
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  purchases_ui_flutter: ^6.16.1
  back_button_interceptor: ^7.0.0
  google_mobile_ads: ^4.0.0
  user_messaging_platform: ^1.3.0
  purchases_flutter: ^6.19.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  flutter_bugfender: ^2.1.2
  firebase_crashlytics: ^3.4.10
  appsflyer_sdk: ^6.12.2
  rate_my_app: ^2.0.0
  flutter_rating_bar: ^4.0.1

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  change_app_package_name: ^1.1.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/welcome_image.png
    - assets/images/3d-model.jpg
    - assets/images/anime.jpg
    - assets/images/cinematic.jpg
    - assets/images/comic-book.jpg
    - assets/images/digital-art.jpg
    - assets/images/enhance.jpg
    - assets/images/fantasy-art.jpg
    - assets/images/isometric.jpg
    - assets/images/line-art.jpg
    - assets/images/low-poly.jpg
    - assets/images/modeling-compound.jpg
    - assets/images/neon-punk.jpg
    - assets/images/origami.jpg
    - assets/images/photographic.jpg
    - assets/images/pixel-art.jpg
    - assets/images/tile-texture.jpg
    - assets/placeholder.png
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/image4.png
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/4.png
    - assets/5.png
    - assets/6.png
    - assets/7.png
    - assets/8.png